import { IInitialStateVideoData } from "../types";
import preview from "../assets/preview.jpg";

export const initialVideoData: IInitialStateVideoData = {
  video: [
    {
      id: 1,
      title: "Pilot",
      image: preview,
      season: "1 season",
      series: 1,
      description: `Rick, in a drunken state, takes his grandson, Morty, for a ride in his flying car and rambles on about how he plans to use a neutrino bomb to wipe out all life on Earth. Rick lands the vehicle on Morty's demand and passes out. The bomb activates by itself and seems to be left unchecked, but ultimately it is shown that life on Earth remains intact. After having breakfast with their family, Rick takes Morty to another dimension to collect seeds of "Mega Trees", which Morty is forced to hide in his own rectum to get past intergalactic customs. However, Rick and Morty's cover is blown and they escape while engaging in a shootout with alien insect soldiers. Ultimately, the seeds briefly cause Morty to be highly intelligent, despite the fact that he missed a semester of school because he's been in adventures with Rick. This causes his parents to believe he is fine with his education, but this wastes the seeds, so Rick informs Morty that they need to go back and get more, while their aftereffects leave Morty writhing on the floor.`,
    },
    {
      id: 2,
      title: "Lawnmower Dog",
      image: preview,
      season: "1 season",
      series: 2,
      description: `On Jerry's demand, Rick gives Snuffles, the family dog, an intelligence-enhancing helmet. Rick and Morty, in an Inception-esque scenario, enter the dream of Morty's teacher, in an attempt to make him give Morty an "A" in math class. They find themselves in a dangerous situation, where they are forced to repeatedly enter dreams within dreams to escape. Eventually, they are chased by a dream character named Scary Terry, a "legally safe" parody of Freddy Krueger. They manage to enter his dream, where they stand up for him against his bully teacher. This persuades Scary Terry to help them complete their mission. Meanwhile, at home, Snuffles builds a mechanical suit and assembles a dog army intending to take over Earth. Returning home from their adventure, Rick and Morty enter Snuffles' dream, where Rick causes Morty to fall into a coma. This prompts Snuffles to rethink his priorities, resulting in him taking his army to another planet.`,
    },
    {
      id: 3,
      title: "Anatomy Park",
      image: preview,
      season: "1 season",
      series: 3,
      description: `On Christmas, Rick sends Morty inside the body of a homeless man to save his life (a parody of Fantastic Voyage). Inside the man's body is a microscopic enclosure called Anatomy Park (a parody of Jurassic Park), which houses various deadly diseases that escape their enclosures. Morty and one of the park staff, Annie, flee from the rampaging diseases as they kill the rest of the base staff. Rick rescues them by enlarging the homeless man's body to the width of the US before destroying it in an explosion. Back at the family home, Jerry's parents visit, and the family attempts to bond without electronic devices. Jerry is dismayed to discover his parents have decided to try polyamory.`,
    },
    {
      id: 4,
      title: "M. Night Shaym-Aliens!",
      image: preview,
      season: "1 season",
      series: 4,
      description: `Aliens hold Rick and Jerry captive in a virtual reality, in an attempt to steal Rick's recipe for Concentrated Dark Matter. As Rick attempts escape, he discovers that there are multiple virtual reality layers on top of each other. Jerry, on the other hand, despite numerous system glitches, remains completely oblivious, and keeps trying to sell his advertising slogan for apples. Rick finally games the aliens by giving them a fake recipe. The aliens send Rick and Jerry on their way, and their ship explodes as they prepare the concoction.`,
    },
    {
      id: 5,
      title: "Meeseeks and Destroy",
      image: preview,
      season: "1 season",
      series: 5,
      description: `After killing deadly enemies in an alternative dimension, Morty complains that Rick's adventures are too dangerous and traumatizing. This leads them into a "Jack and the Beanstalk" type adventure, where Morty is in charge. He decides to steal the giant's treasure and give it to the villagers. The giant dies by accident, Rick and Morty are charged with murder but are ultimately acquitted. Rick and Morty then descend from the Giants' beanstalk realm and stop in a fairy tale pub on the way down. There, King Jellybean attempts to rape Morty, but Morty escapes. Rick wins money playing poker and gives it to the villagers. As Rick and Morty are leaving this dimension, Rick kills King Jellybean, having figured out his attempted rape of Morty. Meanwhile, Beth, Summer and Jerry use Rick's "Meeseeks Box" to spawn Meeseeks, blue creatures that fulfill one request and then explode. Jerry summons one Meeseeks to help him improve his golf game, and spends some time training, to no avail. The Meeseeks summons more of them to help, resulting in a increasingly larger crowd of frustrated Meeseeks. They decide to kill Jerry, but given one last chance, he ultimately demonstrates that his skills actually have improved and the Meeseeks are happy to disappear.`,
    },
    {
      id: 6,
      title: "Rick Potion #9",
      image: preview,
      season: "1 season",
      series: 6,
      description: `Morty is interested in going to the dance at his school with his classmate Jessica, so he asks Rick for a love potion. However, because Jessica has the flu, the potion becomes airborne and goes haywire, causing not only her but the whole population of Earth to fall for Morty save for blood relatives. Rick attempts to fix up an antidote, but he fails twice, ultimately causing all humans affected by the love potion to turn into mutated monsters called "Cronenbergs" (a reference to famous director of body horror films David Cronenberg). Meanwhile, Jerry visits Beth in her workplace because he is concerned about her fidelity, and they find Summer later. Rick and Morty then migrate to another dimension where their duplicates died soon after successfully curing all of Earth, thus allowing Rick and Morty to assume their roles.`,
    },
    {
      id: 7,
      title: "Raising Gazorpazorp",
      image: preview,
      season: "1 season",
      series: 7,
      description: `"In a pawn shop in space, Rick buys Morty a sex robot. Soon after, the robot conceives Morty's alien hybrid child whom he names Morty Jr. Rick and Summer go to the sex robot's planet of origin, Gazorpazorp, to find better suited parents for Morty Jr. After discovering that the Gazorpazorpian females are the dominant gender on the planet, Rick and Summer learn that the males of this species mature in only days and are, by nature, extremely violent. The Gazorpazorpian females arrest Rick due to his open misogony and threaten to execute both him and Summer until Summer reveals her fashionable top was made by a man, convincing them to let them go free. Meanwhile, Morty Jr.'s quick aging puts pressure on Morty to try and raise him. Fearing his aggressive instincts, Morty keeps Morty Jr. inside by telling him the air outside is poisonous. However, the isolation causes Morty Jr. to become rebellious. When he realizes Morty lied to him about the air, he gets into a fight with Morty until Rick arrives and prepares to kill Morty Jr. Morty steps in the way of Rick's weapon, telling him he still loves Morty Jr. Morty Jr. decides to move out and live on his own while channeling his aggression into a creative art.`,
    },
    {
      id: 8,
      title: "Rixty Minutes",
      image: preview,
      season: "1 season",
      series: 8,
      description: `As the family watches The Bachelor, Rick is dissatisfied with the quality of Earth TV so he upgrades the cable to show programming from every conceivable dimension. Eventually, they see Jerry on TV as a successful actor in an alternate reality. The family, minus Rick and Morty, uses Rick's goggles to see through the eyes of their duplicates in that alternative reality, where Jerry and Beth have successful lives, they never married, and Summer was never born because Beth had an abortion. Jerry, Beth and Summer have a heated discussion in which they conclude that family life is holding them back and Beth admits that Summer was an unwanted pregnancy. Summer feels unloved and plans to run away, but Morty tells her that he and Rick themselves came from an alternate dimension (as depicted in "Rick Potion #9") and persuades her to stay. Ultimately, Beth and Jerry discover that their alternate selves are miserable in their own ways and witness them getting back together, which convinces them that they also belong together.`,
    },
    {
      id: 9,
      title: "Something Ricked This Way Comes",
      image: preview,
      season: "1 season",
      series: 9,
      description: `Summer works in an antique shop run by the Devil, which gives away items that come with harmful curses. Rick sets up a competitor shop where he uses science to remove the curses, and the Devil is put out of business. Summer helps him to relaunch a successful dot-com company, but he betrays her and keeps the company for himself. Summer and Rick build muscle mass and publicly beat up the Devil to get revenge. Meanwhile, Jerry, helping Morty with his homework, insists that Pluto is a planet. They are abducted by Plutonians to their planet, where Jerry is mistaken for a scientist. His statements about Pluto being a planet make him instantly popular, but it is later revealed to him that Pluto is shrinking due to corporate plutonium mining, and the Plutonian leadership keeps the population distracted by assuring them Pluto is still a planet. Jerry tells the Pluto citizens the truth on a public speech, causing him to be hated and deported back to Earth with Morty.`,
    },
    {
      id: 10,
      title: "Close Rick-Counters of the Rick Kind",
      image: preview,
      season: "1 season",
      series: 10,
      description: `The show's original Rick is wrongfully accused of murdering twenty-seven Ricks from alternate dimensions and kidnapping their respective Mortys. The Trans-Dimensional Council of Ricks arrests him and finds him guilty, upon discovering incriminating evidence which was actually fabricated to frame him. Rick and Morty escape and are chased by a few duplicates of themselves. The Smith household is flooded with other Ricks and Jerry develops a friendship with the good-natured "Doofus Rick". The real culprits seem to be an evil Rick and his Morty. They have been using Mortys' low intelligence brainwaves as a way to conceal themselves. They capture the original Rick and Morty, but the original Morty leads a rebellion of alternate Mortys and releases the original Rick. Rick informs the Council about the real killer, thus clearing his own name. After Rick and Morty depart, the Council discovers that Evil Rick was actually under control by an unknown puppet-master, which was Evil Morty all along. Evil Morty escapes by blending into the crowd of Morties without a Rick`,
    },
    {
      id: 11,
      title: "Ricksy Business",
      image: preview,
      season: "1 season",
      series: 11,
      description: `Jerry and Beth participate in a reenactment of Titanic, but the ship unexpectedly fails to sink. Jerry spends some time alone with Lucy, a female janitor who eventually proves to be a deranged fan of the movie, forcing him to imitate scenes with her at gunpoint. She almost rapes Jerry, but Beth saves him. Meanwhile, Rick is left in charge of Morty and Summer, but they have a large party. Among the guests are teenagers, aliens, Gearhead, Squanchy, alternate Ricks and Abradolf Lincler (a DNA combination of Adolf Hitler and Abraham Lincoln). Not only do they make a mess, but the whole house is accidentally sent into another dimension, where Lincler seemingly dies (he actually survives). Ultimately, the guests are sent away and the house is returned to its place. Rick, Morty and Summer only have minutes to spare before Beth and Jerry arrive, so they use a contraption to freeze time, allowing them to repair the house. They watch Titanic and unanimously agree on how terrible it is.`,
    },
    {
      id: 12,
      title: "A Rickle in Time",
      image: preview,
      season: "2 season",
      series: 1,
      description: `Continuing from "Ricksy Business", Rick, Morty and Summer spend six months repairing the house and screwing around with time frozen. After unfreezing it, the trio ends up in a decaying dimension. They split into separate timelines whenever they are uncertain about something. Rick becomes paranoid, thinking that his duplicates want to kill him, but eventually he calms down. A creature in charge of safeguarding time appears and gives them collars that integrate all the timelines, then attempts to arrest them because Rick stole the time-freezing crystal. Rick, Morty, and Summer show uncertainty on purpose and break the collars, splitting into sixty-four timelines, and they simultaneously beat up the same creature. Rick then repairs the collars, and they successfully integrate all the timelines. In one timeline, Rick attempts to sacrifice himself and let Morty live by giving him his collar, but ultimately he survives too. Meanwhile, Beth and Jerry hit a deer, and bring it to an animal hospital. A hunter claims the deer for his own because he shot it before the accident. Beth is able to save the deer's life and release it.`,
    },
    {
      id: 13,
      title: "Mortynight Run",
      image: preview,
      season: "2 season",
      series: 2,
      description: `Rick takes Morty on a trip to teach him how to pilot the flying car. When Rick realizes that Jerry has followed them without being noticed in the back seat, he leaves him in a daycare specifically designed for Jerries from alternate realities. Jerry socializes with other Jerries, some of them left there indefinitely because their Rick and Morty never returned. Rick sells an antimatter gun to Krombopulous Michael, an alien assassin who intends to use it to eliminate a gaseous being whom Rick nicknames Fart that is held captive by alien authorities. Rick plans to spend the day at the "Blips & Chitz" video arcade, but Morty decides to stop the assassin. After Rick and Morty release Fart, they are chased by the authorities. Fart uses telepathic powers to kill the authorities, which also leads to civilian casualties. Later, Morty learns that Fart wants to eliminate all carbon-based life forms. Morty then kills Fart using Krombopulous Michael's antimatter gun. Rick and Morty return to pick up their Jerry, but it is left unclear whether they got the right one.`,
    },
    {
      id: 14,
      title: "Auto Erotic Assimilation",
      image: preview,
      season: "2 season",
      series: 3,
      description: `Rick attempts to loot a damaged spaceship with Morty and Summer. They find Unity, a hive mind and Rick's ex-lover. It plans to eventually assimilate the whole universe. Beta 7 is a male hive mind who has a crush on Unity, which it rejects. In a planet completely assimilated by Unity, it and Rick have parties, have sex, and drink and use drugs together. In light of all the revelry, it loses control and the planet is left messy and untended. Summer finds the assimilation unethical, until she and Morty witness some inhabitants regain their identities and start a race war. Eventually, Unity decides to leave Rick for its own good. Meanwhile, Beth and Jerry find a secret underground room with a slug-like monster. The couple has an argument where Jerry makes accusations against Rick and Beth tries to defend her father. The monster breaks free of its chains and accuses Beth and Jerry of having the worst relationship it has ever seen. An upset Beth confronts a visibly distressed Rick, who attempts suicide in the garage but fails.`,
    },
    {
      id: 15,
      title: "Total Rickall",
      image: preview,
      season: "2 season",
      series: 4,
      description: `Alien parasites plant fake memories in the minds of the Smith family and pretend they are friends and family members. Every time the family reminisces about the past, the aliens reproduce. The family can't distinguish real people from aliens, so eventually they can't even trust each other. To prevent further spread, Rick locks down the house. At first, the only alien present is the fake "Uncle Steve"; they are soon joined by other aliens including Cousin Nicky, Sleepy Gary (who poses as Beth's husband and Jerry's lover), the family butler Mr. Beauregard, Frankenstein's Monster, a talking pencil named Pencilvester, Tinkles the Fairy Lamb, etc. Mr. Poopybutthole is an unusual yellow creature who did not appear in any previous episode but appears to be a longtime friend. Eventually, Morty discovers that the parasites can only create positive memories, allowing the Smith family to confirm one another's existence and kill all the aliens. Beth mistakes Mr. Poopybutthole for a parasite and shoots him.`,
    },
    {
      id: 16,
      title: "Get Schwifty",
      image: preview,
      season: "2 season",
      series: 5,
      description: `A massive alien head (a "Cromulon") appears over Earth, demanding to hear an original song, so Rick and Morty improvise "Get Schwifty". The whole planet is abducted and forced to participate in a musical talent show, where the losers' planets are obliterated via plasma ray. Morty steals Rick's portal gun and leaves him alone with Ice-T to make a hit original song and save earth. Morty stumbles across Birdperson (living with Tammy since S1E11 episode Ricksy Business), who persuades him to go back to Rick. Ice-T is revealed to be an ice alien who does not initially care about Earth, but he later changes his mind and saves the planet. Rick, Morty, and the US president win the competition by improvising "Head Bent Over". Meanwhile, Jerry, Beth, and Summer enter a religious cult based on an incorrect interpretation of the message from Cromulons. The movement quickly disbands after realizing it was all a musical talent show.`,
    },
    {
      id: 22,
      title: "The Rickshank Rickdemption",
      image: preview,
      season: "3 season",
      series: 1,
      description: `Rick is interrogated via a mind-computer link, inside a galactic federal prison. Summer and Morty attempt to rescue him but they are captured by SEAL Team Ricks, who take them to the Citadel of Ricks and decide to assassinate Rick. Back at the prison, Rick tricks both the federal agents and his aspiring assassins by switching bodies with them. He then teleports the entire Citadel into the federal prison, prompting a massive battle. Amid the confusion, Rick rescues Morty and Summer, and uses the Galactic Federation's mainframe to make its currency worthless. The Federation falls into chaos and collapses as a result, with the aliens leaving Earth. Rick, Morty, and Summer return home where Jerry gives Beth an ultimatum to choose between him and Rick. Beth chooses Rick and the couple decide to get a divorce. After the new status quo is established, Rick reveals to Morty that his ulterior motive was to become his de facto male influence and get revenge at Jerry for threatening to turn him in to authorities. This escalates into a monologue, centered around Rick's desire to find more of the discontinued McDonald's Szechuan sauce, a promotional product for the 1998 film Mulan.`,
    },
  ],
  currentSeason: [],
  currentVideo: {},
};
